# Generated by Django 5.2.10 on 2026-01-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_jewelryitem_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelryitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost Price (€)'),
        ),
        migrations.AlterField(
            model_name='jewelryitem',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Selling Price (€)'),
        ),
    ]
